project:
  type: website
  output-dir: ../docs

website:
  title: "LaBB-CAT Documentation"
  favicon: favicon.ico
  twitter-card: 
    description: "Information, How-to, exercises, and documentation about the LaBB-CAT corpus management system."
    creator: "@robertfromont"
    site: "@labbcat"
  open-graph: true

  sidebar: 
    style: floating
    search: true
    contents: 
      - href: index.qmd
        text: Home
      - section: worksheets/index.qmd
        contents: 
          - section: worksheets/demo/index.qmd
            contents: 
              - href: worksheets/demo/1-exploration.qmd
              - href: worksheets/demo/2-search.qmd
              - href: worksheets/demo/3-celex.qmd
              - href: worksheets/demo/4-alignment.qmd
              - href: worksheets/demo/5-syntax.qmd
              - href: worksheets/demo/6-other-processing.qmd
          - section: worksheets/express-tutorial/index.qmd
            contents: 
              - href: worksheets/express-tutorial/1-install-and-configure-labb-cat.qmd
              - href: worksheets/express-tutorial/2-upload-data.qmd
              - href: worksheets/express-tutorial/3-basic-searching.qmd
              - href: worksheets/express-tutorial/4-cmudict-and-cross-layer-search.qmd
          - section: worksheets/course/index.qmd
            contents:
              - href: worksheets/course/1-installation.qmd
              - href: worksheets/course/2-setting-up.qmd
              - href: worksheets/course/3-uploading-data.qmd
              - href: worksheets/course/4-searching.qmd
              - href: worksheets/course/5-manual-annotation.qmd
              - href: worksheets/course/6-automatic-annotation.qmd
              - section: worksheets/course/7-lexicon.qmd
                contents:
                  - href: worksheets/course/7a-lexicon-celex.qmd
                  - href: worksheets/course/7b-lexicon-cmudict.qmd
              - section: worksheets/course/8-forced-alignment.qmd
                contents:
                  - href: worksheets/course/8a-forced-alignment-htk.qmd
                  - href: worksheets/course/8b-forced-alignment-mfa.qmd
              - href: worksheets/course/9-aligned-data.qmd
#      - section: howto/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    copyright: "© 2023 NZILBB"
    license: CC BY-SA
    description-meta: "Information, how-to, exercises, and documentation about the LaBB-CAT corpus management system."
    author-meta: "Robert Fromont"
#  pdf:
#    documentclass: scrreprt