project:
  type: website
  output-dir: ../docs

website:
  title: "LaBB-CAT Documentation"
  favicon: favicon.ico
  twitter-card: 
    description: "Information, How-to, exercises, and documentation about the LaBB-CAT corpus management system."
    creator: "@robertfromont"
    site: "@labbcat"
  open-graph: true

  sidebar: 
    style: floating
    search: true
    contents: 
      - href: index.qmd
        text: Home
      - section: worksheets/index.qmd
        contents: 
          - section: worksheets/demo/index.qmd
            contents: worksheets/demo/*
          - section: worksheets/express-tutorial/index.qmd
            contents: worksheets/express-tutorial/*
          - section: worksheets/course/index.qmd
            contents:
              - href: worksheets/course/1-installation.qmd
              - href: worksheets/course/2-setting-up.qmd
              - href: worksheets/course/3-uploading-data.qmd
              - href: worksheets/course/4-searching.qmd
              - href: worksheets/course/5-manual-annotation.qmd
              - href: worksheets/course/6-automatic-annotation.qmd
              - section: worksheets/course/7-lexicon.qmd
                contents:
                  - href: worksheets/course/7a-lexicon-celex.qmd
                  - href: worksheets/course/7b-lexicon-cmudict.qmd
              - section: worksheets/course/8-forced-alignment.qmd
                contents:
                  - href: worksheets/course/8a-forced-alignment-htk.qmd
                  - href: worksheets/course/8b-forced-alignment-mfa.qmd
              - href: worksheets/course/9-aligned-data.qmd
      - section: howto/index.qmd
        contents:
          - section: "Transcription"
            contents: howto/transcription/*
          - href: howto/word-frequency/index.qmd
          - section: "Phonemic Tagging"
            contents: howto/phonemic-tagging/*
          - section: howto/forced-alignment/index.qmd
            contents:
              - href: howto/forced-alignment/bas-services-manager.qmd
              - href: howto/forced-alignment/htk-p2fa.qmd
              - href: howto/forced-alignment/htk-train-align.qmd
              - href: howto/forced-alignment/mfa-pretrained-models.qmd
              - href: howto/forced-alignment/mfa-train-align.qmd
              - href: howto/forced-alignment/compare.qmd
              - href: howto/forced-alignment/identifying-unaligned-utterances.qmd
          - section: howto/aligned-data/index.qmd
            contents: howto/aligned-data/*
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    copyright: "© 2023-2024 NZILBB"
    license: CC BY-SA
    description-meta: "Information, how-to, exercises, and documentation about the LaBB-CAT corpus management system."
    author-meta: "Robert Fromont"
