name: Generate PDFs

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Install
        uses: pandoc/actions@main/setup
        with:
          version: 2.19

      - name: Run pandoc
        run: pandoc -o course.pdf course/home.html
